### ISSUE TITLE
refactor cookbook for etcd 2.0

### ISSUE THREAD

**Issue by willejs** [spheromak/etcd-cookbook#41]
I made some changes on my own [fork](https://github.com/willejs/etcd-cookbook/tree/etcd-2.0) to run etcd 2.0 and realised that the vast amount of config changes might warrant a refactor of the cookbook.

Im wondering if we move to LWRP's or just move the cluster cookbook logic into the library?

I feel like LWRP's would be a cleaner implementation however.

Thoughts?

**Comment by heyryanw** [comment]
I had to do the same [here](https://github.com/heyryanw/etcd-cookbook), but it's not what I'd call "code complete" to match all new options available and removed in 2.0+.

LWRPs seem like the way to go to turn options on/off, since there's a lot of flags you'd not want as default in 2.0, like the '-name' option.

**Comment by spheromak** [comment]
@willejs yes moving the HWRP / LWRP more in the spirit of what Sean has done on the httpd cookbook makes sense to me. This is what I would like to see, and what makes sense.

**Comment by spheromak** [comment]
@willejs I've added you as collaborator on the repo. I think just starting work on a branch on this repo towards the L/HWRP ends makes sense.

**Comment by willejs** [comment]
@spheromak thanks. I am currently migrating to 2.0 in production.
Apparently they are working on better migration documentation this week which may shed more light on the subject. However, it looks as if bootstrapping new nodes to the cluster is now slightly more involved, and im unsure how to automate this so far.

**Comment by spheromak** [comment]
Yea It's one reason I haven't tackled this yet. Haven't gone through it in prod. Also I've started a new job which is eating up a lot of time.

**Comment by anoldguy** [comment]
@willejs, is your master branch the latest work on this topic?  We're looking at moving to 2.0, but I don't want to re-invent the wheel if you've got something that's working.

**Comment by willejs** [comment]
@anoldguy it works but is pretty shonky.im using it in production but adding new nodes you need to do different steps, and I can't think of an elegant way to automate this all...

**Comment by willejs** [comment]
Anyone come up with any ideas?

**Comment by MikeTLive** [comment]
there are a number of etcd cookbooks to be found here on github.
with this one as the source_url for https://supermarket.chef.io/cookbooks/etcd

a new etcd-v2 cookbook has recently emerged
https://github.com/rapid7/chef-etcd
https://supermarket.chef.io/cookbooks/etcd-v2

could they be combined for the benefit of the many who have now downloaded them both?

**Comment by spheromak** [comment]
@MikeTLive  I offered to hand that namespace over to whoever wants to actively maintain.

**Comment by MikeTLive** [comment]
Well, I'm game if no one else wants to take it on. I need an etcd cookbook and would rather see unity than forking.

**Comment by jmanero-r7** [comment]
I'm not sure that there's any benefit in trying to merge rapid7/chef-etcd with this codebase as the interface is completely different. You're more likely to introduce breaking changes to consumers without version locking IMO. Rather, if @spheromak is no longer interested in maintaining this repo, he could deprecate it in favor of the etcd-v2 cookbook (see https://supermarket.chef.io/cookbooks/kafka).

**Comment by spheromak** [comment]
@MikeTLive @jmanero-r7  who wants to take it over ? I am happy to hand it off.  Or to mark it deprecated.  Just need to know what the best course of action is here.

**Comment by spheromak** [comment]
Going to hand this over to the chef-brigade repo. Anyone interested can take up maintainership there.

**Comment by spheromak** [comment]
@MikeTLive @jmanero-r7  It's moved. If you or anyone else is interested in working on this thing. Join the chef-brigade! also moved the cook in supermarket to the brigade.
