### ISSUE TITLE
The manually-specified cluster members are not actually configured

### ISSUE THREAD

**Issue by ajardan** [spheromak/etcd-cookbook#42]
When I specify etcd.nodes = ["node1", "node2"], all I get is a file - /etc/etcd_members.

That file is not loaded as -peers-file, so the attribute has no effect.

I temporarily solved this by setting etcd.args = "-peers-file=/etc/etcd_members", but it looks like a bug to me, as the Readme doesn't mention any other actions while setting up the cluster manually.

Should I send a patch that fixes this ?

**Comment by ajardan** [comment]
I ended up writing my own cookbook that supports 2.x and has most of the features of this cookbook.

The only missing feature is auto-finding nodes from a chef-server, which is easy to implement in the future if required.

**Comment by ajardan** [comment]
Here it is: https://github.com/Assembla/chef-etcd

**Comment by spheromak** [comment]
@ajardan if you want to take over the supermarket for this I would be happy to depreciate this cookbook for yours.

**Comment by ajardan** [comment]
@spheromak why not, let's try that.

**Comment by ajardan** [comment]
@spheromak So, how do we do that ?
